muenzpraeger/create-lwc-app

CHANGELOG.md, packages/lwc-create-app/package.json, packages/lwc-services/package.json
=> Increase min required node version for packages to 10.0

packages/lwc-create-app/src/generators/createGenerator.ts
=> Change git email check

packages/lwc-services/src/messages/serve.ts, packages/lwc-services/src/messages/watch.ts
=> Message updates

packages/lwc-services/src/commands/test.ts, packages/lwc-services/src/messages/test.ts
=> Added pass through support for command line arguments to lwc-jest.

.prettierignore, packages/lwc-create-app/templates/scripts/express-dev.js, packages/lwc-create-app/templates/src/client/modules/my/app/app.html, packages/lwc-create-app/templates/src/server/index.js
=> Express server additions

packages/lwc-services/src/utils/webpack/webpack-builder.ts
=> Fixing TS resolve of imported modules

packages/create-lwc-app/src/generators/createGenerator.ts
=> Fixing concurrent npm scripts

packages/lwc-services/src/commands/serve.ts
=> Fix custom Express config for TS projects

packages/lwc-services/src/config/lwcConfig.ts, packages/lwc-services/src/utils/webpack/module-loader.ts
=> Add new parameter for stylesheet configs in LWC compiler

packages/lwc-services/src/utils/webpack/module-resolver.ts
#104 solves the error `Module not found: Error: Can't resolve './foo.html' in ...` in a pure library with `export default class Foo {}` during the build command.
This PR solves the issue in which you import a missing file (a template) from your component code, and still don't get any error in the build process. The default template should be provided only if the template (`<cmpname>.html`) that is added by the `@lwc/compiler` does not exist.
**Repro:**
filesystem:
modules/cmp/cmp.js
`cmp.js` code:
```js
import { LightningElement } from 'lwc';
import tpl from './tpl.html';
export default class Cmp extends from LightningElement {
render() {
return tpl;
}
}
```
**Current behavior**: No error is shown on build command
**Expected behavior**: An error similar to `Module not found: Error: Can't …
=> fix: no error when importing missing template

packages/create-lwc-app/src/generators/createGenerator.ts
=> fix: 🐛 wrong JS setup in advanced mode

packages/create-lwc-app/src/generators/createGenerator.ts, packages/create-lwc-app/src/index.ts, packages/create-lwc-app/src/messages/create.ts, packages/create-lwc-app/src/messages/createGenerator.ts
=> feat: move node version check to CLI init

packages/lwc-services/src/utils/webpack/module-resolver.ts
- Removed extra path checks used by Webpack LWC Module Resolver Plugin ran before lwc module plugin. Retained simple regex check, as it looks like LWC will try to resolve module config before differentiating between a standard npm module and one containing modules. 
- Use issuer (importer) path instead of cwd to properly resolve modules with nested lwc configs. 
- Removed unused functions in file
Test project here: https://github.com/dexwiz/lwc-module-loader-test Set up a new Typescript project via create-lwc-app and added an npm dependency to sanity check it would still properly load non lwc reps.
=> Removed redundant module checks before LWC Module Resolver

packages/create-lwc-app/templates/lwc-services.config.js
=> fix: removes duplicate entry in lwc-services.config.json

packages/create-lwc-app/templates/lwc-services.config.js
=> fix: copy sub-folders in resources for Rollup

packages/lwc-webpack-plugin/package.json, packages/lwc-webpack-plugin/src/loader.ts
Fixes #760 
Will be published this week
=> feat: add optional chaining for TypeScript in LWC Webpack plugin

packages/create-lwc-app/package.json, packages/lwc-services/package.json, packages/lwc-services/src/config/webpack.config.ts, yarn.lock
=> fix: remove error overlay plugin

packages/create-lwc-app/templates/src/client/modules/my/greeting/greeting.js, packages/create-lwc-app/templates/src/client/modules/my/greeting/greeting.ts
Hello I've added Arabic in greetings files (both TS and JS greetigs files ). 
Thanks :) !!!
=> adding arabic greetings marhaba

packages/create-lwc-app/src/generators/createGenerator.ts
=> fix: project description is now saved

packages/lwc-services/src/commands/build.ts, packages/lwc-services/src/commands/sniff.ts, packages/lwc-services/src/commands/watch.ts, packages/lwc-services/src/messages/build.ts, packages/lwc-services/src/messages/sniff.ts, packages/lwc-services/src/messages/watch.ts
I need the ability to customize the `HtmlWebpackPlugin` to add a content security policy meta tag, as well as to customize the behavior of the DefinePlugin.
=> Add ability to override webpack plugins
